### ISSUE TITLE
Adding to the database

### ISSUE THREAD

**Issue by georgeorgeorge** [philipbjorge/Infinite-Social-Wall#9] opened 2012-07-23 08:58 UTC
Hi there,

I seem to be experiencing an issue where after the initial setup of the config.php file and the changing of the file permissions, nothing is being added to the database. 

I am 100% sure my MySQL settings are correct as I have tested them and added to the database through a test page. I have also added dummy data to see if it was a connection issue and it seems to be as nothing is being pulled in.

Is there anything else I have to edit in order to make this work. Or have you found this issue in the past and know what the solution might be? Your help on this is greatly appreciated. I would love to get this working too as it looks and IS awesome. 

Thanks

George

**Comment by philipbjorge** [comment] 2012-07-23 14:18
I'll have a look at this after work today/tomorrow. In the mean time, can
you tell me what version of PHP you're running and a feed you're trying to
hit?

So you've added test data to the social wall database table? What happens
if you go to get_stream.php directly?
On Jul 23, 2012 1:58 AM, "georgeorgeorge" <
reply@reply.github.com>
wrote:

**Comment by georgeorgeorge** [comment] 2012-07-23 15:34
5.3.3 Is the PHP version I'm running. I'm trying to pull in pinterest, twitter and instagr.am (statigr.am) feeds. I have checked them to see if they are returning anything and they are.

I made some slight progress whereby my dummy content was appearing but nothing was being added to the database. I'm wondering if it might be something to do with the permissions on the files perhaps?

when you go directly to get_stream.php nothing happens either, just a WSOD!

**Comment by philipbjorge** [comment] 2012-07-23 15:47
That sounds plausible - can you try temporarily changing the server
permissions to something more flexible on all the php files? 0755 maybe.

Are you on shared hosting?
On Jul 23, 2012 8:34 AM, "georgeorgeorge" <
reply@reply.github.com>
wrote:

**Comment by philipbjorge** [comment] 2012-07-23 15:49
get_stream.php?p=0 returns a WSOD with the dummy content in the database?

What about get_stream.php?p=update ?

**Comment by philipbjorge** [comment] 2012-07-23 15:52
Are you trying to run this in a subdirectory (e.g.
http://domain.com/wall/demo.php)?
On Jul 23, 2012 8:34 AM, "georgeorgeorge" <
reply@reply.github.com>
wrote:

**Comment by georgeorgeorge** [comment] 2012-07-23 16:59
You absolute gem! After changing the permissions to 755 on pretty much everything and then running the ?p=update string got it going. Thank you so much for your time. You have truly made something awesome.

**Comment by voroda** [comment] 2012-07-23 17:08
Hi mate,

I am experiencing the same issue. I have added dummy contents and  the script is working (SQL and Isotope display) but the social networks feeds are not pulled. I'm using PHP Version 5.3.5 and I have the following message 'Deprecated: Assigning the return value of new by reference is deprecated in lib\simplepie.inc'. I tried to update the simplepie file with the latest version without any sucess . I also tried to run your script without subdirectory and it is not working. I think simplepie is not working correctly with PHP 5.3.5 or XAMPP. 
Does anyone have any ideas? 

Great job anyway

**Comment by voroda** [comment] 2012-07-23 17:12
Sorry after running the ?p=update string It is working Great job. Thanks

**Comment by georgeorgeorge** [comment] 2012-07-23 21:40
Hello, I'm back!

In solving this issue, I think I may have come across another potential issue.

While using the string to update the database manually works perfectly, it does not seem to be updating automatically after 15+ minutes have past on the cache.

How does the cache work exactly and what do you think could be the potential cause of this? permissions are on 755 by the way for all files and folders.

Thanks for your time and hard work in making this.

**Comment by philipbjorge** [comment] 2012-07-23 21:51
The database is updated when the index page is hit - the updated contents are then added to the user's browser. A request is made to get_stream.php?p=update
https://github.com/philipbjorge/Infinite-Social-Wall/blob/master/js/jquery.infinitesocialwall.js#L38

Depending on how your directory structure is setup, this query might be getting a 404. For example, if you have the following directory structure:
/wall/demo.php
/scripts/get_stream.php

then it wouldn't find the file because it'd look in /wall/get_stream.php.

If the issue is just that you want the script to update every 15 minutes, regardless of if user's are visiting the site, then I'd recommend using a cron job.

The cache works by stopping the RSS feed reader from hitting the servers again unless 15 minutes have passed since it last did it.

**Comment by georgeorgeorge** [comment] 2012-07-25 11:27
I have not changed the file structure from the download zip file. I've never set up a cron job before so this is new to me but I'll look into it.

**Comment by philipbjorge** [comment] 2012-07-25 14:15
So then visiting your social wall should cause the update page to be called in the background. if new items are found they get added to the visitors page (like in the video demo).

If you get a visitor before 10 new posts (on each feed) have happened, then you won't miss anything. otherwise you can setup a cron job in cpanel.

a cronjob runs a command on a schedule. yours would be something like:

wget http://georgegeorge.com/get_stream.php?p=update

Feel free to contact me through my website and I can check out your page and see if I can debug the problem.

**Comment by georgeorgeorge** [comment] 2012-07-26 08:47
I see they get loaded into an element with the ID 'new-content' but that element does not seem to exist anywhere in the code. Is that element being dynamically generated elsewhere?

**Comment by georgeorgeorge** [comment] 2012-07-26 09:09
I have found a solution!

If you have an element pre-existing in the index.php page with the ID 'new-content' it hits the update there and then. 

My one concern with this is if it loads in the content on everyones first visit will it kill the server? 

Obviously I dont expect many people to be visiting my own personal site but for future developments and larger scale site do you think this is a viable option?

**Comment by philipbjorge** [comment] 2012-07-26 14:26
I really appreciate the debugging georgegeorge - I'll know exactly what to better document. sorry for being a beta tester :).

That's a good point - if you start getting a lot of concurrent hits, its possible that the RSS feeds would update many times missing the cache because X number of users hit update all at the same time after 15 minutes.

A fix for this would be to remove the client side update and have a cronjob on the server hitting update periodically. I'll mention this in a Readme update.

**Comment by philipbjorge** [comment] 2012-07-26 14:28
Normally, if a user hits the cache within 15 minutes of another user it doesn't load anything.

**Comment by georgeorgeorge** [comment] 2012-07-27 08:15
Hey, no need to be sorry! I've loved playing around with this platform. The fact that you think I'm helping too makes it all the more worthwhile.

While looking into cron jobs, I came across this nice little article. 

http://net.tutsplus.com/tutorials/php/managing-cron-jobs-with-php-2/

Do you think it might be worthwhile setting up a library like this so that eventual users of this wont have to set a cron job up manually? Just a thought really but could potentially take this platform to the next level.

**Closed as completed** 2012-07-29 20:48 UTC
